### ISSUE TITLE
some confusion.

### ISSUE THREAD

**Issue by zhaigz** [djukicn/loca#8]
Hi, I am a bit confused about your code, and I would greatly appreciate it if you could answer my questions. 
<img width="535" alt="Snipaste_2024-04-22_17-18-42" src="https://github.com/djukicn/loca/assets/80504435/6f6a5bb2-c671-465d-84f3-d08d49d4a57d">
For example,near 150 in the ope. py file . What is the purpose of the for loop in the above code? Why do we need to perform three layer operations on the output and put each result output into outputs? What is the difference between output and outputs. Only one layer can obtain processed num_objects=3 prototypes？
If it's convenient, I hope to receive your reply as soon as possible. Thank you

**Comment by Aurora-zgz** [comment]
<img width="366" alt="Snipaste_2024-04-22_17-27-46" src="https://github.com/djukicn/loca/assets/80504435/022f722f-b095-443b-b8c9-089ee30d2eff">
In the above image, the value 27 of the 0th dimension in "appearance" already includes the prototype of all num_objects? Because it is obtained from self. num_objects * self. kernel_dim * * 2. 
<img width="327" alt="Snipaste_2024-04-22_17-34-29" src="https://github.com/djukicn/loca/assets/80504435/93c85d03-4ae4-487f-910d-daea95b6c4e0">
So the shape of "all_prototypes" obtained from the ope. py function is (3,27,1,256), and what does 3 in the 0th dimension mean? num_objects? But isn't num_objects included in 27 in the first dimension? I don't understand.

**Comment by djukicn** [comment]
Hi @Aurora-zgz, thank you for your question.

As you correctly noted, as single `IterativeAdaptationLayer` can handle an arbitrary number of objects. However, to achieve iterative adaptation, we stack a number (in this case 3) of such layers to create the `IterativeAdaptationModule`. The iteration you mention goes over layers and not over objects, so the line `output = layer(output)` just says that the input to the next layer is the output of the previous layer. You can see the exact same thing in the `transformer.py` file, lines 32-36. This is the same as packing your layers in the `nn.Sequential` object and not using the loop.

Why the `outputs` list? Basically, we just gather the output of every layer in this list. We need this because we apply auxiliary losses to intermediate layers (see more details in the paper). Therefore, the 0th dimension in `all_prototypes` refers to the number of layers in the `IterativeAdaptationModule` (it's probably a bit confusing because both the number of objects and adaptation layers is 3 but try changing one and you will see the difference).

Let me know if this helps.

**Comment by zhaigz** [comment]
Thank you very much for your reply. The explanation was very clear and helpful to me.

**Comment by Aurora-zgz** [comment]
In addition, I also found that when visualizing the `loca_few_shot.pt `generated by reproducing the code, the quantity counted each time is different, and the difference is significant. In contrast, the pre trained `loca_few_shot.pt` you provided does not have this issue and the quantity is relatively accurate.

**Comment by Aurora-zgz** [comment]
@djukicn Regarding Val COCO and Test COCO, I would like to know how they were obtained. Is it possible to directly extract Val COCO and Test COCO from FSC147 for verification and testing? What is the specific experimental process like? I don't quite understand according to the description in the paper. I would greatly appreciate it if you could provide me with a timely answer.
